# Dev stuff
auto: true

# Website config
title: "Julien Fantin"
tagline: "Software developer, iOS aficionado."
tagline_long: "Seeking collaboration within a team of passionate hackers."
future: no
pygments: yes

# Each section will link to a file in ./pages/
# The filename should contain no uppercase and no spaces
sections:
  - About
  - Resume
  - Blog

# Status updates
work_status: "I'm available for work, hire me!"
location: "France"
